version: '3'
services:
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
  mariadb:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=default
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
