version: '3'
services:
  web:
    build: .
    user: root
    ports:
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - mariadb
  mariadb:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=default
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
