-- MySQL Script generated by MySQL Workbench
-- Tue Jan 18 13:04:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema lab1_schema1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lab1_schema1` ;

-- -----------------------------------------------------
-- Schema lab1_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab1_schema1` ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTMENT` (
  `DeptNo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`DeptNo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `EmpNo` INT NOT NULL,
  PRIMARY KEY (`EmpNo`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `lab1_schema1` ;

-- -----------------------------------------------------
-- Table `lab1_schema1`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_schema1`.`Customer` (
  `CustNo` CHAR(8) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `PhoneNo` VARCHAR(45) NULL,
  `CustBal` VARCHAR(45) NULL,
  PRIMARY KEY (`CustNo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab1_schema1`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_schema1`.`Employee` (
  `EmpNo` CHAR(8) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `PhoneNo` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`EmpNo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab1_schema1`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_schema1`.`Order` (
  `OrderNo` CHAR(8) NOT NULL,
  `OrderDate` VARCHAR(45) NULL,
  `CustName` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `PhoneNo` VARCHAR(45) NULL,
  `Customer_CustNo` CHAR(8) NOT NULL,
  `Employee_EmpNo` CHAR(8) NULL,
  PRIMARY KEY (`OrderNo`),
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`Customer_CustNo`)
    REFERENCES `lab1_schema1`.`Customer` (`CustNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_EmpNo`)
    REFERENCES `lab1_schema1`.`Employee` (`EmpNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Order_Customer_idx` ON `lab1_schema1`.`Order` (`Customer_CustNo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Order_Employee1_idx` ON `lab1_schema1`.`Order` (`Employee_EmpNo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab1_schema1`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_schema1`.`Product` (
  `ProdNo` CHAR(8) NOT NULL,
  `ProdName` VARCHAR(45) NULL,
  `Mfg` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  PRIMARY KEY (`ProdNo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab1_schema1`.`ProductInOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_schema1`.`ProductInOrder` (
  `Qty` INT NOT NULL,
  `Order_OrderNo` CHAR(8) NOT NULL,
  `Product_ProdNo` CHAR(8) NOT NULL,
  PRIMARY KEY (`Qty`, `Order_OrderNo`, `Product_ProdNo`),
  CONSTRAINT `fk_ProductInOrder_Order1`
    FOREIGN KEY (`Order_OrderNo`)
    REFERENCES `lab1_schema1`.`Order` (`OrderNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductInOrder_Product1`
    FOREIGN KEY (`Product_ProdNo`)
    REFERENCES `lab1_schema1`.`Product` (`ProdNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ProductInOrder_Order1_idx` ON `lab1_schema1`.`ProductInOrder` (`Order_OrderNo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ProductInOrder_Product1_idx` ON `lab1_schema1`.`ProductInOrder` (`Product_ProdNo` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
