name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Test query
        run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/query/INSERT%20INTO%20%27lab1_schema1%27.%27Employee%27%20%28%27EmpNo%27%2C%20%27FirstName%27%2C%20%27LastName%27%2C%20%27PhoneNo%27%2C%20%27Email%27%29%20VALUES%20%28%271%27%2C%20%27Tom%27%2C%20%27Chan%27%2C%20%2723456789%27%2C%20%27tomchan%40gmail.com%27%29
      - name: Get RowsAffected
        run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/status
